const SET_THEME_LIGHT = 'SET_THEME_LIGHT'
const SET_THEME_DARK = 'SET_THEME_DARK'
const LIKE_POST = 'LIKE_POST'
const DISLIKE_POST = 'DISLIKE_POST'

export {SET_THEME_DARK, SET_THEME_LIGHT, LIKE_POST, DISLIKE_POST}